services:
  services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "5000:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://35.208.188.12:3000/ || exit 1"]
      interval: 10s
      retries: 5
      start_period: 5s


 frontend:
  build:
    context: .
    dockerfile: Dockerfile.frontend
  container_name: frontend
  depends_on:
    backend:
      condition: service_healthy
  ports:
    - "3000:80"

