services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: backend_${BUILD_NUMBER}
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 10s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend_${BUILD_NUMBER}
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:80"
