version: "3.9"

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:3000"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  authbd:
    build:
      context: ../services/AuthDB
      dockerfile: Dockerfile
    container_name: authbd
    ports:
      - "4000:4000"
    volumes:
      - ../services/AuthDB/serviceAccountKey.json:/app/serviceAccountKey.json:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/serviceAccountKey.json

  location:
    build:
      context: ../services/Location
      dockerfile: Dockerfile
    container_name: location
    ports:
      - "4001:4001"
